# Main Menu (header)

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

# Footer Menu

[[footer]]
  name = "GitHub"
  url = "https://github.com/skillicinski"
  weight = 10
